#ifndef XING_LOG_HH
#define XING_LOG_HH

#include "soil/Log.hh"

#define XING_LOG_INIT(x) SOIL_LOG_INIT(x)

#define XING_TRACE SOIL_TRACE
#define XING_DEBUG SOIL_DEBUG
#define XING_INFO  SOIL_INFO
#define XING_WARNING SOIL_WARNING
#define XING_ERROR SOIL_ERROR
#define XING_FATAL SOIL_FATAL
#define XING_PDU SOIL_PDU
#define XING_CUSTOM SOIL_CUSTOM


#endif

